### ISSUE TITLE
Luminaries sort is not accounting for capitalization

### ISSUE THREAD

**Issue by mixcas** [interglobalvision/pindropstudio-com#23]

**Comment by varffs** [comment]
What do you mean accounting? It sorts by slugs so everything sorted will be lowercase no?

**Comment by mixcas** [comment]
its sorting by surname which is a metabox

**Comment by varffs** [comment]
oh yh that is now meta. well its a easy fix just lowercase the string in the js sorting function

**Comment by mixcas** [comment]
better do it in the server
